// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Game = require("./Game.bs.js");
var Prime = require("./Prime.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

require('primereact/resources/themes/saga-blue/theme.css')
;

require('primereact/resources/primereact.min.css')
;

require('primeicons/primeicons.css')
;

require('primeflex/primeflex.css')
;

Prime.Utils.init(true);

var root = document.querySelector("#app");

if (!(root == null)) {
  ReactDom.render(React.createElement(Game.make, {}), root);
}

/*  Not a pure module */
