// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDom = require("react-dom");
var PlayerSetup = require("./PlayerSetup.bs.js");

var root = document.querySelector("#app");

if (!(root == null)) {
  ReactDom.render(React.createElement(PlayerSetup.make, {}), root);
}

/* root Not a pure module */
