// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Player = require("./Player.bs.js");
var PlayerSetup = require("./PlayerSetup.bs.js");

function Game(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var match$1 = React.useState(function () {
        return false;
      });
  var setGameStarted = match$1[1];
  if (match$1[0] === false) {
    return React.createElement(PlayerSetup.make, {
                playerCount: match[0],
                setPlayerCount: match[1],
                setGameStarted: setGameStarted
              });
  } else {
    return React.createElement(Player.make, {
                initialName: "lolo",
                isWinner: false,
                setIsWinner: setGameStarted,
                isOpaque: false
              });
  }
}

var make = Game;

exports.make = make;
/* react Not a pure module */
