// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Inputtext = require("primereact/inputtext");

function Player$CardHeader(Props) {
  var playerName = Props.playerName;
  var setPlayerName = Props.setPlayerName;
  var isWinner = Props.isWinner;
  var onPlayerNameChanged = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setPlayerName, (function (_prev) {
                  return value;
                }));
  };
  var selectAllOnFocus = function (evt) {
    console.log(evt.target);
    
  };
  if (isWinner) {
    return React.createElement("span", {
                className: "winner-text"
              }, "🏆 " + playerName + " wins! 👑");
  } else {
    return React.createElement(Inputtext.InputText, {
                className: "name-field",
                value: playerName,
                onChange: onPlayerNameChanged,
                onFocus: selectAllOnFocus
              });
  }
}

var CardHeader = {
  make: Player$CardHeader
};

function Player(Props) {
  var initialName = Props.initialName;
  var isWinner = Props.isWinner;
  var match = React.useState(function () {
        return initialName;
      });
  return React.createElement("div", {
              className: "player-panel p-col-fixed",
              style: {
                width: "320px"
              }
            }, React.createElement(Player$CardHeader, {
                  playerName: match[0],
                  setPlayerName: match[1],
                  isWinner: isWinner
                }));
}

var make = Player;

exports.CardHeader = CardHeader;
exports.make = make;
/* react Not a pure module */
