// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Button = require("primereact/button");
var Inputtext = require("primereact/inputtext");

function PlayerSetup(Props) {
  var playerCount = Props.playerCount;
  var setPlayerCount = Props.setPlayerCount;
  var setGameStarted = Props.setGameStarted;
  var match = React.useState(function () {
        return false;
      });
  var setShowError = match[1];
  var onClick = function (param) {
    if (playerCount >= 3 && playerCount <= 10) {
      Curry._1(setShowError, (function (param) {
              return false;
            }));
      return Curry._1(setGameStarted, (function (param) {
                    return true;
                  }));
    } else {
      return Curry._1(setShowError, (function (param) {
                    return true;
                  }));
    }
  };
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setPlayerCount, (function (_prev) {
                  return value;
                }));
  };
  return React.createElement("div", {
              className: "grid",
              style: {
                marginTop: "15px",
                marginLeft: "15px"
              }
            }, React.createElement("div", {
                  className: "col-4 sm:col-6"
                }, React.createElement("div", {
                      className: "field p-component"
                    }, React.createElement("label", {
                          className: "block"
                        }, "How many players are going to play?"), React.createElement(Inputtext.InputText, {
                          className: "block",
                          value: playerCount.toString(),
                          onChange: onChange
                        }), match[0] ? React.createElement("div", {
                            className: "error-text"
                          }, "Please enter a number between 3 and 10.") : null), React.createElement(Button.Button, {
                      label: "Start Game",
                      onClick: onClick
                    })));
}

var make = PlayerSetup;

exports.make = make;
/* react Not a pure module */
