// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Inputtext = require("primereact/inputtext");

function PlayerSetup(Props) {
  return React.createElement("div", {
              className: "p-grid"
            }, React.createElement("div", {
                  className: "p-col-4 p-col-sm-6"
                }, React.createElement("div", {
                      className: "p-field p-component"
                    }, React.createElement("label", {
                          className: "p-d-block"
                        }), React.createElement(Inputtext.InputText, {}))));
}

var make = PlayerSetup;

exports.make = make;
/* react Not a pure module */
