// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("primereact/utils");

var InputText = {};

var Button = {};

var Panel = {};

function init(ripple) {
  Utils.ripple = ripple;
  
}

var Utils$1 = {
  init: init
};

exports.InputText = InputText;
exports.Button = Button;
exports.Panel = Panel;
exports.Utils = Utils$1;
/* primereact/utils Not a pure module */
